[package]
name = "biirubot"
version = "0.1.0"
authors = ["Jyri Genral <jyri.genral@protonmail.ch>"]
#edition = "2021"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kuchiki = "0.8"